name: "Obrazul auto release tag"
description: "Automatically generate next release tag incrementally with year, month and iteration based on previous release tag."
author: "obrazul"
branding:
  color: "blue"
  icon: "tag"

inputs:
  github_token:
    description: "Github secrets token"
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
